import type { Metadata } from 'next';
import { Sarabun, Oxanium } from 'next/font/google';
import './globals.css';
import Navbar from './components/Sections/NavBar';
import Footer from './components/Sections/Footer';

const sarabun = Sarabun({
  subsets: ['latin'],
  variable: '--font-sarabun',
  weight: ['200', '800'],
});
const oxanium = Oxanium({
  subsets: ['latin'],
  variable: '--font-oxanium',
  weight: ['200', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${oxanium.variable} ${sarabun.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
